name: Run API Tests

on:
 push:
   branches: [main]
 workflow_dispatch:
 schedule:
  - cron: '30 2 * * *'  #8.00 AM IST
  - cron: '30 13 * * *' #7.00 AM IST


jobs:
  run-tests:
    runs-on: ubuntu-latest
    steps:
     - name: Checkout Code
       uses: actions/checkout@v3

     - name: Setup Node
       uses: actions/setup-node@v3
       with:
         node-version: '18'

     - name: Install Newman
       run: |
          npm install -g newman
          npm install -g newman-reporter-htmlextra

     - name: Run Collection
       run: |
        newman run 'In-warranty-flow-Collections.postman_collection.json' \
          -e QA.postman_environment.json \
          -d testdata.csv \
          -r cli,htmlextra \
          --reporter-htmlextra-export ./newman/index.html
          

     - name: Newman report
       if: always() #It will execute this step whether previuos step is failed
       uses: actions/upload-artifact@v4.6.2
       with:
         name: newman-html-report
         path: newman/*.html

     - name: Creating GitHub pages branch
       if: always()
       uses: peaceiris/actions-gh-pages@v4.0.0
       with:
         github_token: ${{ secrets.github_token }}
         publish_dir: newman/

         
